### GET request to example server
GET http://localhost:3002/api/orders

###

POST http://localhost:3002/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJqYW5la0BzZXIucGwiLCJpYXQiOjE3Njc4NTMxMDQsImV4cCI6MTc2Nzg1NjcwNH0.FSsyYV7RIG-msOqHFDwgoNLrSe8jUYk6wMPg_qQkL1xiQYWFVM6L5LXB5wufemd6

{
  "userId": 1,
  "bookId": 1,
  "quantity": 5
}