###
GET http://localhost:8080/api/books

###

POST http://localhost:8080/api/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJzZXJvd3lAc2VyLnBsIiwiaWF0IjoxNzY3ODkxMzQwLCJleHAiOjE3Njc4OTQ5NDB9.OOaGFv5B6nPtQT2SwMuo3A9y_4Civofc3WtqDG5OyyxUrDDGQd9h6mitBggWPKG6

{
    "title": "Wiedźmin",
    "author": "Sapkowski",
    "publicationYear": 1993
}
###

DELETE http://localhost:8080/api/books/2

###

GET http://localhost:8080/api/books/2