###
GET http://localhost:8080/api/books

###

POST http://localhost:8080/api/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJqYW5la0BzZXIucGwiLCJpYXQiOjE3Njc4NTMxMDQsImV4cCI6MTc2Nzg1NjcwNH0.FSsyYV7RIG-msOqHFDwgoNLrSe8jUYk6wMPg_qQkL1xiQYWFVM6L5LXB5wufemd6

{
    "title": "Wiedźmin",
    "author": "Sapkowski",
    "publicationYear": 1993
}
###

DELETE http://localhost:8080/api/books/2

###

GET http://localhost:8080/api/books/2